/* Exploratory Data Analysis (EDA):
   Where I explore the data and it's metadata and answer some key questions.
   Exploring all objects in the database
*/
SELECT * FROM INFORMATION_SCHEMA.TABLES;

--Exploring all columns in the database;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customer';

--Dimension Exploration:
--Explore all countries our customer comes from
SELECT DISTINCT country FROM gold.dim_customers;

--Explore all categories "The major Division"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3;

--First and Last order date
SELECT
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(year, MIN(order_date),MAX(order_date)) AS Year_range,
	DATEDIFF(month, MIN(order_date),MAX(order_date)) AS month_range
FROM gold.fact_sales;

--Find the youngest and oldest customers
SELECT
	MIN(birthdate) AS youngest_cust,
	DATEDIFF(year, MIN(birthdate),GETDATE()) AS Oldest_age,
	MAX(birthdate) AS oldest_cust,
	DATEDIFF(year, MAX(birthdate),GETDATE()) AS youngest_age
FROM gold.dim_customers;


--Find the total sales
SELECT SUM(sales_amount) total_sales FROM gold.fact_sales;

--Find how many items are sold
SELECT SUM(quantity) total_quantity FROM gold.fact_sales;

--Find the average selling price
SELECT AVG(price) avg_price FROM gold.fact_sales;

--Find the total number of orders (Remove duplicates)
SELECT COUNT(DISTINCT order_number) total_orders FROM gold.fact_sales;

--Find the total number of product
SELECT COUNT(product_key) total_product FROM gold.dim_products;
SELECT COUNT(DISTINCT product_key) total_product FROM gold.dim_products;

--Find the total number of customer
SELECT COUNT(customer_key) total_customer FROM gold.dim_customers;
SELECT COUNT(DISTINCT customer_key) total_customer FROM gold.dim_customers;

--Find the total number of customer that has placed an order
SELECT COUNT(DISTINCT customer_key) total_customer FROM gold.fact_sales;


--Generate a report that shows all key metrics of the business:
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Product' AS measure_name, COUNT(DISTINCT product_key) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total Customers' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.dim_customers;



--Find total customers by countries
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


--Find total customers by gender
SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


--Find total products by categories
SELECT 
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

--What is the average costs in each category?
SELECT 
	category,
	AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

--What is the total revenue generated for each category?
SELECT 
	p.category,
	SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


--Find the total revenue is generated by each customer?
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP by
	c.customer_key,
	c.first_name,
	c.last_name	
ORDER by total_revenue DESC;


--What is the distribution of sold items across countries?
SELECT
	c.country,
	SUM(s.quantity) AS total_sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP by
	c.country
ORDER by total_sold_items DESC;



--Which 5 Products generate the highest revenue?
SELECT  TOP 5 
	p.product_name,
	SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

--Another approach
SELECT * FROM(
SELECT  
	p.product_name,
	SUM(s.sales_amount) AS total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount) DESC) AS rank_products
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
)t WHERE rank_products <= 5;

--What are the 5 worst-performing products in terms of sales?
SELECT  TOP 5 
	p.product_name,
	SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;

--Another approach
SELECT * FROM(
SELECT  
	p.product_name,
	SUM(s.sales_amount) AS total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount) ASC) AS rank_products
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
)t WHERE rank_products <= 5;


--Find the 5 top performing customers with highest orders?
SELECT TOP 5
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP by
	c.customer_key,
	c.first_name,
	c.last_name	
ORDER by total_orders DESC;



--Find the 3 customers with fewest orders?
SELECT TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP by
	c.customer_key,
	c.first_name,
	c.last_name	
ORDER by total_orders ASC;
